global:
  scrape_interval: 30s

scrape_configs:
  - job_name: vmagent
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: victoriametrics
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: app
    static_configs:
      - targets: ['app:8081']
  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']