---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 9121
    prometheus.io/scrape: 'true'
  name: redis
  namespace: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: metrics
  selector:
    app: redis
