{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service_name=\"faraway-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application request duration (95%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service_name=\"faraway-app\"})) by(le, code))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}