apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: victoria-metrics-single-0.8.53
  name: victoria
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: victoria
subjects:
- kind: ServiceAccount
  name: victoria
  namespace: monitoring
