apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: victoria-metrics-single-0.8.53
  name: victoria-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: victoria-clusterrole
subjects:
- kind: ServiceAccount
  name: victoria
  namespace: monitoring
