apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: server
    app.kubernetes.io/instance: victoria
    app.kubernetes.io/name: victoria
    helm.sh/chart: victoria-metrics-single-0.8.53
  name: victoria-server
  namespace: monitoring
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: server
      app.kubernetes.io/instance: victoria
      app.kubernetes.io/name: victoria
  serviceName: victoria-server
  template:
    metadata:
      labels:
        app: server
        app.kubernetes.io/instance: victoria
        app.kubernetes.io/name: victoria
        helm.sh/chart: victoria-metrics-single-0.8.53
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --retentionPeriod=6
        - --storageDataPath=/storage
        - -promscrape.config=/scrapeconfig/scrape.yml
        - --envflag.enable=true
        - --envflag.prefix=VM_
        - --loggerFormat=json
        image: victoriametrics/victoria-metrics:v1.87.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8428
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        name: victoria-server
        ports:
        - containerPort: 8428
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /storage
          name: server-volume
          subPath: null
        - mountPath: /scrapeconfig
          name: scrapeconfig
      serviceAccountName: victoria
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: victoria-server-scrapeconfig
        name: scrapeconfig
      - name: server-volume
        emptyDir: {}